# Pandas Basics — Part 3

In this lesson, we're going to introduce more fundamentals of [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html), a powerful Python library for working with tabular data like CSV files.

We will review skills learned from the last two lessons and introduce how to:

- Clean and transform data
- Identify values with `.loc` and `.iloc`
- Manipulate string data
- Apply functions
- Reset index

## Dataset
### *The Pudding*'s Film Dialogue Data

```{epigraph}
Lately, Hollywood has been taking so much shit for rampant sexism and racism. The prevailing theme: white men dominate movie roles.
But it’s all rhetoric and no data, which gets us nowhere in terms of having an informed discussion. How many movies are actually about men? What changes by genre, era, or box-office revenue? What circumstances generate more diversity?
```
-- Hannah Anderson and Matt Daniels, ["Film Dialogue from 2,000 screenplays, Broken Down by Gender and Age"](https://pudding.cool/2017/03/film-dialogue/)

The dataset that we're working with in this lesson is taken from Hannah Andersen and Matt Daniels's *Pudding* essay, ["Film Dialogue from 2,000 screenplays, Broken Down by Gender and Age"](https://pudding.cool/2017/03/film-dialogue/). The dataset provides information about 2,000 films from 1925 to 2015, including characters’ names, genders, ages, how many words each character spoke in each film, the release year of each film, and how much money the film grossed. They included character gender information because they wanted to contribute data to a broader conversation about how "white men dominate movie roles."

Yet transforming complex social constructs like gender into quantifiable data is tricky and historically fraught. They claim, in fact, that one of the [most frequently asked questions](https://medium.com/@matthew_daniels/faq-for-the-film-dialogue-by-gender-project-40078209f751) about the piece is about gender: “Wait, but let’s talk about gender. How do you know the monster in Monsters Inc. is a boy!" The short answer is that they don't. To determine character gender, they used actors' IMDB information, which they acknowledge is an imperfect approach: "Sometimes, women voice male characters. Bart Simpson, for example, is voiced by a woman. We’re aware that this means some of the data is wrong, AND we’re still fine with the methodology and approach."

While approaches like this are often the best we can do, it's still worth stoping to ask: what do we lose because of these reductive approaches to gender? What harms might they bring about, and are there cases where the harms outweigh the benefits?

## Import Pandas

In [ ]:
import pandas as pd

## Set Display Settings

By default, Pandas will display 60 rows and 20 columns. I often change [pandas' default display settings](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html) to show more rows or columns.

In [ ]:
pd.options.display.max_rows = 100

## Download file

In [ ]:
# For downloading large files from Google Drive
import gdown

# Download the first json file, "rev0-rests.json"
gdown.download('https://drive.google.com/uc?export=download&id=1c57rPwI_8fe1crOIWlhQi_CXFqLBK9nq', quiet=False)

## Read in CSV File

To read in a CSV file, we will use the function `pd.read_csv()` and insert the name of our desired file path.

In [ ]:
film_df = pd.read_csv('Pudding-Film-Dialogue-Clean.csv', delimiter=",", encoding='utf-8')

When reading in the CSV file, we also specified the `encoding` and `delimiter`. The `delimiter` parameter specifies the character that separates or "delimits" the columns in our dataset. For CSV files, the delimiter will most often be a comma. (CSV is short for *Comma Separated Values*.) Sometimes, however, the delimiter of a CSV file might be a tab (`/t`) or, more rarely, another character.

## Display Data

We can display a DataFrame in a Jupyter notebook simply by running a cell with the variable name of the DataFrame.

`NaN` is the Pandas value for any missing data. See ["Working with missing data"](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html?highlight=nan) for more information.

In [ ]:
film_df

There are a few important things to note (or remember) about the DataFrame displayed here:

* Index
    * The ascending numbers in the very left-hand column of the DataFrame is called the Pandas *Index*. You can select rows based on the Index.
    * By default, the Index is a sequence of numbers starting with zero. However, you can change the Index to something else, such as one of the columns in your dataset. We'll do this down below.

* Truncation
    * The DataFrame is truncated, signaled by the ellipses in the middle `...` of every column.
    * The DataFrame is truncated because we set our default display settings to 100 rows. Anything more than 100 rows will be truncated. To display all the rows, we would need to alter Pandas' default display settings yet again.

* Rows x Columns
    * Pandas reports how many rows and columns are in this dataset at the bottom of the output (23,048 x 10 columns).

### Summary Statistics

In [ ]:
film_df.describe(include='all')

Do you notice any outliers, anomalies, or potential problems here?

*Hint: Look at the maximum value in the age column. Does that make sense?*

## .loc vs. .iloc

The main distinction between the two methods is:

* `loc` gets rows (and/or columns) with particular labels.
* `iloc` gets rows (and/or columns) at integer locations.

Let's see if we can use one of these methods to find and replace that weird age entry:

In [ ]:
film_df[film_df['age'] == 2013]

Let's edit this value from the dataset by using the `.iloc()` method and the Index number of the row.

In [ ]:
film_df.loc[11639, ['age']] = 43

Now if we look for that row again, the value at that particular location has changed:

In [ ]:
film_df.loc[11639]

## Clean and Transform Data

### Pandas `.str` Methods

Pandas has special [pandas string methods](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#string-methods). Many of them are very similar to Python string methods, except they will transform every single string value in a column, and we have to add `.str` to the method chain.

| **Pandas String Method** | **Explanation**                                                                                   |
|:-------------:|:---------------------------------------------------------------------------------------------------:|
| df['column_name']`.str.lower()`         | makes the string in each row lowercase                                                                                |
| df['column_name']`.str.upper()`         | makes the string in each row uppercase                                                |
| df['column_name']`.str.title()`         | makes the string in each row titlecase                                                |
| df['column_name']`.str.replace('old string', 'new string')`      | replaces `old string` with `new string` for each row |
| df['column_name']`.str.contains('some string')`      | tests whether string in each row contains "some string" |
| df['column_name']`.str.split('delim')`          | returns a list of substrings separated by the given delimiter |
| df['column_name']`.str.join(list)`         | opposite of split(), joins the elements in the given list together using the string                                                                        |

For example, to transform every character's name in the "character" column from lowercase to uppercase, we can use `.str.upper()`

In [ ]:
film_df['character'].str.upper()

To transform every character's name in the "character" column to lowercase, we can use `.str.lower()`

In [ ]:
film_df['character'].str.lower()

We can use the `.str.contains()` to search for particular words or phrases in a column, such as "Star Wars."

In [ ]:
film_df[film_df['title'].str.contains('Star Wars')]

We can use the `.str.contains()` to search for particular words or phrases in a column, such as "Mean Girls."

In [ ]:
film_df[film_df['title'].str.contains('Mean Girls')]

## Applying Functions

With the `.apply()` method, we can run a function on every single row in a Pandas column or dataframe.

In [ ]:
def make_text_title_case(text):
    title_case_text = text.title()
    return title_case_text

In [ ]:
make_text_title_case("betty")

In [ ]:
film_df['character'].apply(make_text_title_case)

In [ ]:
film_df['character'] = film_df['character'].apply(make_text_title_case)

In [ ]:
film_df.sample(10)

### Filter DataFrame

We can filter the DataFrames for only characters who are men or women.

In [ ]:
men_film_df = film_df[film_df['gender'] == 'Man']
men_film_df.head()

In [ ]:
women_film_df = film_df[film_df['gender'] == 'Woman']
women_film_df.head()

### Groupby

We can use the `.groupby()` function to group all the men characters in each film and sum up their total dialogue.

By adding a Python string slice, we can identify the top 20 films with the greatest proportion of men speaking.

In [ ]:
men_film_df.groupby('title')[['proportion_of_dialogue']].sum().sort_values(by='proportion_of_dialogue', ascending=False)[:20]

We can use the `.groupby()` function to group all the women characters in each film and sum up their total dialogue.

By adding a Python string slice, we can identify the top 20 films with the greatest proportion of women speaking.

In [ ]:
women_film_df.groupby('title')[['proportion_of_dialogue']].sum().sort_values(by='proportion_of_dialogue', ascending=False)[:20]

## Reset Index

We can transform a Groupby object into a DataFrame with a regular Index by tacking on `.reset_index()`.

In [ ]:
women_film_df.groupby('title')[['proportion_of_dialogue']].sum().sort_values(by='proportion_of_dialogue', ascending=False).reset_index()

_Dan Sinkyin adapted this notebook from Melanie Walsh's [Pandas Basics — Part 3](https://melaniewalsh.github.io/Intro-Cultural-Analytics/features/Data-Analysis/Pandas-Basics-Part3.html) in 2020. Lauren Klein updated it in 2021 and 2022._